### ISSUE TITLE
Maven Release

### ISSUE THREAD

**Issue by gamma** [fracpete/rsync4j#38]
As far as I can see, the information on this page: https://fracpete.github.io/rsync4j/maven/ is not correct. https://mvnrepository.com/artifact/com.github.fracpete/rsync4j lists 3.1.2-8 as the latest release.

Can you please update the maven release? Can that be automated to ensure new releases in the maven repository?

**Comment by fracpete** [comment]
As always, the devil is in the details. You were referring to the `rsync4j` artifact, but my documentation lists the `rsync4j-all` artifact. mvnrepository lists the latest version as well:
https://mvnrepository.com/artifact/com.github.fracpete/rsync4j-all

And yes, the deployment process is automated (has always been).

The `rsync4j` artifacts dates from a time before I split the library into:
* `core`: just Java (Linux/Mac)
* `winX`:  for Windows 32/64 bit (the 32bit version has been dropped since as cygwin no longer supports win32)
* `all`: which combines all modules

**Comment by gamma** [comment]
Thanks for clearing this up!

**Comment by fracpete** [comment]
I've added the available modules with a short description to the same page now: https://fracpete.github.io/rsync4j/maven/
